/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type FranchisePackage = {
  _id: string;
  _type: "franchisePackage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  price?: string;
  priceNote?: string;
  features?: Array<string>;
  featured?: boolean;
  order?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Merchandise = {
  _id: string;
  _type: "merchandise";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  price?: number;
  originalPrice?: number;
  badge?: "BESTSELLER" | "NEW";
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tokopediaUrl?: string;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Tournament = {
  _id: string;
  _type: "tournament";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  date?: string;
  location?: string;
  prize?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Promo = {
  _id: string;
  _type: "promo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  isHot?: boolean;
  title?: string;
  description?: string;
  validInfo?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order?: number;
};

export type Branch = {
  _id: string;
  _type: "branch";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  zone?: string;
  name?: string;
  city?: string;
  province?: string;
  address?: string;
  tables?: number;
  tags?: Array<string>;
  openHour?: string;
  closeHour?: string;
  mapsUrl?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order?: number;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | FranchisePackage
  | SanityImageAssetReference
  | Merchandise
  | SanityImageCrop
  | SanityImageHotspot
  | Tournament
  | Promo
  | Branch
  | AuthorReference
  | CategoryReference
  | Post
  | BlockContent
  | Author
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {    _id,    title,    slug,    mainImage,    publishedAt,    "excerpt": pt::text(body[0..1]),    "author": author->{ name },    "categories": categories[]->{ title }  }
export type ALL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
  excerpt: string;
  author: {
    name: string | null;
  } | null;
  categories: Array<{
    title: string | null;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    title,    slug,    mainImage,    publishedAt,    body,    "author": author->{ name, image },    "categories": categories[]->{ title }  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
  body: BlockContent | null;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  categories: Array<{
    title: string | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: ALL_POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)] {    "slug": slug.current  }
export type ALL_POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: ALL_BRANCHES_QUERY
// Query: *[_type == "branch"] | order(order asc) {    _id, zone, name, city, province, address, tables, tags, openHour, closeHour, mapsUrl, photo  }
export type ALL_BRANCHES_QUERY_RESULT = Array<{
  _id: string;
  zone: string | null;
  name: string | null;
  city: string | null;
  province: string | null;
  address: string | null;
  tables: number | null;
  tags: Array<string> | null;
  openHour: string | null;
  closeHour: string | null;
  mapsUrl: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: ALL_PROMOS_QUERY
// Query: *[_type == "promo"] | order(order asc) {    _id, label, isHot, title, description, validInfo, photo  }
export type ALL_PROMOS_QUERY_RESULT = Array<{
  _id: string;
  label: string | null;
  isHot: boolean | null;
  title: string | null;
  description: string | null;
  validInfo: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: ALL_TOURNAMENTS_QUERY
// Query: *[_type == "tournament"] | order(date asc) {    _id, name, date, location, prize, photo  }
export type ALL_TOURNAMENTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  date: string | null;
  location: string | null;
  prize: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: ALL_MERCHANDISE_QUERY
// Query: *[_type == "merchandise"] | order(order asc) {    _id, name, price, originalPrice, badge, photo, tokopediaUrl  }
export type ALL_MERCHANDISE_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  price: number | null;
  originalPrice: number | null;
  badge: "BESTSELLER" | "NEW" | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  tokopediaUrl: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: ALL_FRANCHISE_PACKAGES_QUERY
// Query: *[_type == "franchisePackage"] | order(order asc) {    _id, name, price, priceNote, features, featured  }
export type ALL_FRANCHISE_PACKAGES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  price: string | null;
  priceNote: string | null;
  features: Array<string> | null;
  featured: boolean | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    mainImage,\n    publishedAt,\n    "excerpt": pt::text(body[0..1]),\n    "author": author->{ name },\n    "categories": categories[]->{ title }\n  }\n': ALL_POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    mainImage,\n    publishedAt,\n    body,\n    "author": author->{ name, image },\n    "categories": categories[]->{ title }\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': ALL_POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "branch"] | order(order asc) {\n    _id, zone, name, city, province, address, tables, tags, openHour, closeHour, mapsUrl, photo\n  }\n': ALL_BRANCHES_QUERY_RESULT;
    '\n  *[_type == "promo"] | order(order asc) {\n    _id, label, isHot, title, description, validInfo, photo\n  }\n': ALL_PROMOS_QUERY_RESULT;
    '\n  *[_type == "tournament"] | order(date asc) {\n    _id, name, date, location, prize, photo\n  }\n': ALL_TOURNAMENTS_QUERY_RESULT;
    '\n  *[_type == "merchandise"] | order(order asc) {\n    _id, name, price, originalPrice, badge, photo, tokopediaUrl\n  }\n': ALL_MERCHANDISE_QUERY_RESULT;
    '\n  *[_type == "franchisePackage"] | order(order asc) {\n    _id, name, price, priceNote, features, featured\n  }\n': ALL_FRANCHISE_PACKAGES_QUERY_RESULT;
  }
}
